[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_10-DeepLearning/blob/master/Th10_CC_DJ_Deep_Learning_CC__2.ipynb)

# Softmax

The Softmax Function is the final step in a CNN, it takes the outputs from the final layer of neurons and transforms them to be probability values between 0 and 1. In this way, instead of a vector of voting weights, we end up with a vector of probabilities where there is a single probability for each label/class. This is how our CNN makes its final classification predictions.

From Wikipedia: [Softmax Function](https://en.wikipedia.org/wiki/Softmax_function)

"The Softmax Function... is a generalization of the logistic function that "squashes" a K-dimensional vector of arbitrary real values to a K-dimensional vector of real values, where each entry is in the range (0, 1), and all the entries add up to 1."

$S(y_i) = \frac{e^{y_i}}{\sum_{j=1}^Je^{y_j}}$
---





# Do It

Write your own softmax function from scratch that will work on both 1-D and 2-D matrices. 

The following inputs should yield the given outputs:

### 1-D input: 

$\begin{bmatrix}
  1 & 2 & 3 & 6 \\
\end{bmatrix}$

### 1-D output: 

 Notice that the values in this matrix add up to 1 and are scaled exponentially.

$\begin{bmatrix}
  0.00626879 & 0.01704033 & 0.04632042 & 0.93037047 \\
\end{bmatrix}$

### 2-D input:

$\begin{bmatrix}
  1 & 2 & 3 & 6 \\
  2 & 4 & 5 & 6 \\
  3 & 8 & 7 & 6 \\
\end{bmatrix}$

### 2-D output:

Notice that each row in the 2-D output adds up to 1. 

$\begin{bmatrix}
  0.00626879 & 0.01704033 &  0.04632042 & 0.93037045] \\
  0.01203764 & 0.08894681 & 0.24178252 & 0.657233 \\
   0.00626879 & 0.01704033 & 0.04632042 & 0.93037045 \\
\end{bmatrix}$




In [0]:
import numpy as np

softmax1d = lambda y : np.exp(y)/np.sum(np.exp(y))

oneD = np.array([1.0, 2.0, 3.0, 6.0])
twoD = np.array([[1.0,2.0,3.0,6.0],[2.0,4.0,5.0,6.0], [3.0,8.0,7.0,6.0]])


In [37]:
softmax1d(oneD)

array([0.00626879, 0.01704033, 0.04632042, 0.93037047])

In [40]:
print(softmax1d(twoD))

[[4.89907947e-04 1.33170787e-03 3.61995731e-03 7.27087861e-02]
 [1.33170787e-03 9.84006416e-03 2.67480676e-02 7.27087861e-02]
 [3.61995731e-03 5.37249300e-01 1.97642972e-01 7.27087861e-02]]


In [39]:
print(softmax1d(twoD[0]))
print(softmax1d(twoD[1]))
print(softmax1d(twoD[2]))

[0.00626879 0.01704033 0.04632042 0.93037047]
[0.01203764 0.08894682 0.24178252 0.65723302]
[0.00446236 0.66227241 0.24363641 0.08962882]


In [0]:
output = []
for n in range(3):
  #[softmax1d(twoD[n]) for two in twoD]
  output.append(softmax1d(twoD[n]))

In [41]:
np.array(output)

array([[0.00626879, 0.01704033, 0.04632042, 0.93037047],
       [0.01203764, 0.08894682, 0.24178252, 0.65723302],
       [0.00446236, 0.66227241, 0.24363641, 0.08962882]])

In [0]:
def twoD_max(arry):
  output = []
  for n in range(3):
    output.append(softmax1d(arry[n]))
    
  return np.array(output)

In [43]:
twoD_max(twoD)

array([[0.00626879, 0.01704033, 0.04632042, 0.93037047],
       [0.01203764, 0.08894682, 0.24178252, 0.65723302],
       [0.00446236, 0.66227241, 0.24363641, 0.08962882]])